apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "helm-guestbook.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: networking-svc
  rules:
  - http:
      paths:
      - path: /home
        pathType: Prefix
        backend:
          service:
            name: {{ template "helm-guestbook.fullname" . }}
            port:
              number: 80